version: "3.8"

services:
  alfred-bot:
    container_name: alfred-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/alfred-bot/src
    ports:
      - "4000:4000"

  db:
    container_name: "alfred_db"
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: alfred_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root - TZ=America/Cuiaba
