version: "3.8"

services:
  alfred-bot:
    container_name: alfred-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/alfred-bot/src
    ports:
      - "4000:4000"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alfred
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
