version: "3.8"

services:
  alfred-bot:
    container_name: alfred-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/alfred-bot/src
    ports:
      - "4000:4000"

  db:
    container_name: alfred_db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=alfred_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3308"
    volumes:
      - db:/var/lib/mysql
      - ./src:/alfred-bot/dump/1.sql

volumes:
  db:
    driver: local
